routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'FrontViewController@welcome');

Route::get('/send_sms', 'smsController@sendBird');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('adminLogin');
Route::get('/login/candidat', 'Auth\LoginController@showCandidatLoginForm')->name('candidatLogin');
Route::get('/login/votant', 'Auth\LoginController@showVotantLoginForm')->name('votantLogin');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('adminRegister');
Route::get('/register/candidat', 'Auth\RegisterController@showCandidatRegisterForm')->name('candidatRegister');
Route::get('/register/votant', 'Auth\RegisterController@showVotantRegisterForm')->name('votantRegister');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/candidat', 'Auth\LoginController@candidatLogin');
Route::post('/login/votant', 'Auth\LoginController@votantLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin');
Route::post('/register/candidat', 'Auth\RegisterController@createCandidat');
Route::post('/register/votant', 'Auth\RegisterController@createVotant');

/*Route::get('/admin', 'AdminController@home')->name('admin')->middleware('admin');
Route::view('/votant', 'VotantController@home')->name('votant');
Route::view('/candidat', 'CandidatController@home')->name('candidat');*/



/**
 * All admin routes
 */

Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>['admin'],'as'=>'admin.'], function(){
    //All the admin routes will be defined here...
    Route::get('/', 'AdminController@home')->name('home');
    Route::resource('candidats', 'CandidatController');
    Route::resource('elections', 'ElectionController');
    Route::resource('votes', 'VoteController');
    Route::resource('parties', 'PartyController');
    Route::resource('votants', 'VotantController');
  });


/**
 * All votant routes
 */

Route::group(['prefix'=>'votant','namespace'=>'Votant','middleware'=>['votant'],'as'=>'votant.'], function(){
    //All the votant routes will be defined here...
    Route::get('/', 'VotantController@home')->name('home');
    Route::resource('votes', 'VoteController');
    Route::resource('elections', 'ElectionController');
    Route::resource('parties', 'PartyController');
    Route::post('votes/find_election_party', 'VoteController@findElectionParty')->name('votes.findElectionParty');
  });

 /**
 * All candidat routes
 */

Route::group(['prefix'=>'candidat','namespace'=>'Candidat','middleware'=>['candidat'],'as'=>'candidat.'], function(){
    //All the candidat routes will be defined here...
    Route::get('/', 'CandidatController@home')->name('home');
    Route::resource('votes', 'VoteController');
    Route::resource('parties', 'PartyController');
    Route::resource('elections', 'ElectionController');
  });

app/Election.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Election extends Model
{
    //
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    public function vote()
    {
        return $this->hasMany('App\Vote');
    }

}

app/Http/Controllers/Admin/ElectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Election;
use App\Jobs\ElectionAlert;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ElectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $elections = Election::all();
        return view('admin.election.index', compact('elections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.election.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd(date_create($request->done_at));
        $request->validate([
            'name' => 'required|min:3',
            'description' =>'required|min:3',
            'done_at' => 'required',
        ]);

        $mysqltime = date_create($request->done_at);
        //$x = Carbon::today();
        //Carbon::c
        //dd();
        $election = new Election();
        $election->name = $request->name;
        $election->description = $request->description;
        $election->done_at = $mysqltime;
        $election->save();

        dispatch(new ElectionAlert($election));

        return redirect()->route('admin.elections.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Election::destroy($id);
        return redirect(route('admin.parties.index'));
    }
}

app/Http/Controllers/Candidat/ElectionController.php
<?php

namespace App\Http\Controllers\Candidat;

use App\Election;
use App\Jobs\ElectionAlert;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ElectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $elections = Election::all();
        return view('candidat.election.index', compact('elections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Votant/ElectionController.php
<?php

namespace App\Http\Controllers\Votant;

use App\Election;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ElectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $elections = Election::all();
        return view('votant.election.index', compact('elections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/election/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                    <div class="card-header">
                        <center>
                            <h3>Create Election</h3>
                        </center>
                    </div>

                    <form action="{{ route('admin.elections.store') }}" method="post">
                        <div class="row">
                            @csrf
                            <div class="col-12 p-t-10">
                                <label for="name">Name of election</label>
                            </div>
                            <div class="col-12">
                                <input type="text" name="name" id="name" class="form-control">
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="description">Description of election</label>
                            </div>
                            <div class="col-12">
                                <textarea name="description" id="description" class="form-control" rows="8"></textarea>
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="done_at">date that the election will take place</label>
                            </div>
                            <div class="col-12">
                                <input type="datetime-local" name="done_at" id="" class="form-control">
                            </div>
                            <div class="col-12 p-t-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/election/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row m-t-30">
                <div class="col-md-12">
                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                            <div class="rs-select2--light rs-select2--md">
                                <select class="js-select2" name="property">
                                    <option selected="selected">All Properties</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <div class="rs-select2--light rs-select2--sm">
                                <select class="js-select2" name="time">
                                    <option selected="selected">Today</option>
                                    <option value="">3 Days</option>
                                    <option value="">1 Week</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <button class="au-btn-filter">
                                <i class="zmdi zmdi-filter-list"></i>filters</button>
                        </div>
                        <div class="table-data__tool-right">
                            <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{{ route('admin.elections.create') }}">
                                <i class="zmdi zmdi-plus"></i>add item</a>
                            <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                                <select class="js-select2" name="type">
                                    <option selected="selected">Export</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                        </div>
                    </div>
                    <!-- DATA TABLE-->
                    <div class="table-responsive m-b-40">
                    <h3>List of elections</h3><br>
                        <table class="table table-borderless table-data3">
                            <thead>
                                <tr>
                                    <th>name</th>
                                    <th>description</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($elections as $election)
                                <tr>
                                    <td>{{ $election->name }}</td>
                                    <td>{{ $election->description }}</td>
                                    <td>{{ $election->done_at }}</td>
                                    <td>
                                        <a href="{{ route('admin.elections.destroy', $election->id) }}" class="btn btn-danger btn-sm"
                                           onclick="event.preventDefault(); document.getElementById('delete-form-{{ $election->id }}').submit();">
                                            <i class="fa fa-trash-o text-white"></i>
                                        </a>
                                        <form id="delete-form-{{ $election->id }}" action="{{ route('admin.elections.destroy', $election->id) }}"
                                              method="post" style="display: none;">
                                            @csrf @method('delete')
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE-->
                </div>
            </div>
        </div>
    </div>
@endsection