routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'FrontViewController@welcome');

Route::get('/send_sms', 'smsController@sendBird');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('adminLogin');
Route::get('/login/candidat', 'Auth\LoginController@showCandidatLoginForm')->name('candidatLogin');
Route::get('/login/votant', 'Auth\LoginController@showVotantLoginForm')->name('votantLogin');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('adminRegister');
Route::get('/register/candidat', 'Auth\RegisterController@showCandidatRegisterForm')->name('candidatRegister');
Route::get('/register/votant', 'Auth\RegisterController@showVotantRegisterForm')->name('votantRegister');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/candidat', 'Auth\LoginController@candidatLogin');
Route::post('/login/votant', 'Auth\LoginController@votantLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin');
Route::post('/register/candidat', 'Auth\RegisterController@createCandidat');
Route::post('/register/votant', 'Auth\RegisterController@createVotant');

/*Route::get('/admin', 'AdminController@home')->name('admin')->middleware('admin');
Route::view('/votant', 'VotantController@home')->name('votant');
Route::view('/candidat', 'CandidatController@home')->name('candidat');*/



/**
 * All admin routes
 */

Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>['admin'],'as'=>'admin.'], function(){
    //All the admin routes will be defined here...
    Route::get('/', 'AdminController@home')->name('home');
    Route::resource('candidats', 'CandidatController');
    Route::resource('elections', 'ElectionController');
    Route::resource('votes', 'VoteController');
    Route::resource('parties', 'PartyController');
    Route::resource('votants', 'VotantController');
  });


/**
 * All votant routes
 */

Route::group(['prefix'=>'votant','namespace'=>'Votant','middleware'=>['votant'],'as'=>'votant.'], function(){
    //All the votant routes will be defined here...
    Route::get('/', 'VotantController@home')->name('home');
    Route::resource('votes', 'VoteController');
    Route::resource('elections', 'ElectionController');
    Route::resource('parties', 'PartyController');
    Route::post('votes/find_election_party', 'VoteController@findElectionParty')->name('votes.findElectionParty');
  });

 /**
 * All candidat routes
 */

Route::group(['prefix'=>'candidat','namespace'=>'Candidat','middleware'=>['candidat'],'as'=>'candidat.'], function(){
    //All the candidat routes will be defined here...
    Route::get('/', 'CandidatController@home')->name('home');
    Route::resource('votes', 'VoteController');
    Route::resource('parties', 'PartyController');
    Route::resource('elections', 'ElectionController');
  });

app/Candidat.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Candidat extends Authenticatable
{
    //
    use Notifiable;

    protected $guard = 'candidat';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'phone', 'password',
    ];

    /**
     *
     */
    public function party()
    {
        return $this->hasOne('App\Party');
    }
}

app/Http/Controllers/Admin/CandidatController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Election;
use App\Http\Controllers\Controller;
use App\Jobs\ElectionAlert;
use App\Party;
use Illuminate\Http\Request;

use App\Candidat;
use Illuminate\Support\Facades\Hash;

class CandidatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $candidats = Candidat::all();
        return view('admin.candidat.index', compact('candidats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $parties = Party::all();
        return view('admin.candidat.create', compact('parties'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd(date_create($request->done_at));
        $request->validate([
            'name' => 'required|min:3',
            'email' =>'required|min:3',
            'phone' => 'required',
            'password' => 'required',
            'party_id' => 'required'
        ]);


        $candidat = new Candidat();
        $candidat->name = $request->name;
        $candidat->email = $request->email;
        $candidat->phone = $request->phone;
        $candidat->party_id = $request->party_id;
        $candidat->password = Hash::make($request->password);
        $candidat->save();

        return redirect()->route('admin.candidats.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Candidat::destroy($id);
        return redirect(route('admin.candidats.index'));
    }
}

app/Http/Controllers/Candidat/CandidatController.php
<?php

namespace App\Http\Controllers\Candidat;

use App\Candidat;
use App\Election;
use App\Votant;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;

class CandidatController extends Controller
{
    public function home()
    {

        $elections = count(Election::all());
        $votants = count(Votant::all());
        $candidats = count(Candidat::all());
        return view('candidat.home', compact('elections', 'votants', 'candidats'));
    }
}

app/Http/Controllers/Candidat/ElectionController.php
<?php

namespace App\Http\Controllers\Candidat;

use App\Election;
use App\Jobs\ElectionAlert;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ElectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $elections = Election::all();
        return view('candidat.election.index', compact('elections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Candidat/PartyController.php
<?php

namespace App\Http\Controllers\Candidat;

use App\Http\Controllers\Controller;
use App\Candidat;
use App\Party;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PartyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $parties = Party::with('election')->get();
        return view('candidat.party.index', compact('parties'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $party_id = Candidat::find(Auth::guard('candidat')->id())->party_id;
        $party = Party::find($party_id);
        return view('candidat.party.create', compact('party'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Candidat/VoteController.php
<?php

namespace App\Http\Controllers\Candidat;

use App\Election;
use App\Http\Controllers\Controller;
use App\Party;
use App\Vote;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;

class VoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $voteArray = [];
        $winner = "";
        $election = null;


        $customElections = Election::all();
        foreach ($customElections as $elec) {
            $elecDate = $elec->done_at;

            $electDates = explode(" ", $elecDate);

            if($electDates[0] == explode(" ", date(now()))[0]){
                $election = $elec;
                break;
            }
        }

        // $election = Election::whereDate('done_at','=', date(now()))->get();
        // dd(DB::select("select * from elections where done_at=?", [date(now())]));
        // $election = DB::select("select * from elections where done_at=?", [date(now())]);
        // dd($election);
        if($election == null){
            dd('h');
            return view('candidat.vote.index', compact('voteArray', 'winner', 'election'));
        }
        else{

            // $votes = Vote::where('election_id', $election[0]->id)->get();
            $height = 0;

            $parties = Party::where(['election_id'=>$election->id])->get();
            foreach ($parties as $party) {
                $votes = Vote::where(['election_id'=>$election->id, 'party_id'=>$party->id])->get();
                $voteArrayItem = [
                    "party"=>$party->name,
                    "vote"=>count($votes)
                ];
                if(count($votes) > $height){
                    $winner = $party->name;
                }
                $voteArray[] = $voteArrayItem;
                // dd($voteArray);
            }

            // dd($voteArray);

        }

        return view('candidat.vote.index', compact('voteArray', 'winner', 'election'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Votant/CandidatController.php
<?php

namespace App\Http\Controllers\Votant;

use App\Candidat;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CandidatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //$candidats = Candidat::all();
        //return view('votant.candidat.index', compact('candidats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/candidat/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                    <div class="card-header">
                        <center>
                            <h3>Add candidat</h3>
                        </center>
                    </div>

                    <form action="{{ route('admin.candidats.store') }}" method="post">
                        <div class="row">
                            @csrf
                            <div class="col-12 p-t-10">
                                <label for="name">Name</label>
                            </div>
                            <div class="col-12">
                                <input type="text" name="name" id="name" class="form-control">
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="email">email</label>
                            </div>
                            <div class="col-12">
                                <input type="text" name="email" id="email" class="form-control">
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="phone">phone number</label>
                            </div>
                            <div class="col-12">
                                <input type="number" name="phone" id="" class="form-control">
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="phone">Password</label>
                            </div>
                            <div class="col-12">
                                <input type="text" name="password" id="" class="form-control">
                            </div><br><br>
                            <div class="col-12 p-t-10">
                                <label for="phone">Select Party</label>
                            </div>
                            <select name="party_id" id="select" class="form-control">
                                <option value="0">Please select</option>
                                @foreach ($parties as $party)
                                    <option value="{{ $party->id }}">{{ $party->name }}</option>
                                @endforeach
                            </select>
                            <div class="col-12 p-t-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/candidat/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row m-t-30">
                <div class="col-md-12">
                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                            <div class="rs-select2--light rs-select2--md">
                                <select class="js-select2" name="property">
                                    <option selected="selected">All Properties</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <div class="rs-select2--light rs-select2--sm">
                                <select class="js-select2" name="time">
                                    <option selected="selected">Today</option>
                                    <option value="">3 Days</option>
                                    <option value="">1 Week</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <button class="au-btn-filter">
                                <i class="zmdi zmdi-filter-list"></i>filters</button>
                        </div>
                        <div class="table-data__tool-right">
                            <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{{ route('admin.candidats.create') }}">
                                <i class="zmdi zmdi-plus"></i>add item</a>
                            <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                                <select class="js-select2" name="type">
                                    <option selected="selected">Export</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                        </div>
                    </div>
                    <!-- DATA TABLE-->
                    <div class="table-responsive m-b-40">
                        <table class="table table-borderless table-data3">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>name</th>
                                    <th>phone</th>
                                    <th>email</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($candidats as $candidat)
                                <tr>
                                    <td>1</td>
                                    <td>{{ $candidat->name }}</td>
                                    <td>{{ $candidat->phone}}</td>
                                    <td>{{ $candidat->email }}</td>
                                    <td>
                                        <a href="{{ route('admin.candidats.edit', $candidat->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-pencil text-white"></i></a>
                                        <a href="{{ route('admin.candidats.destroy', $candidat->id) }}" class="btn btn-danger btn-sm"
                                           onclick="event.preventDefault(); document.getElementById('delete-form-{{ $candidat->id }}').submit();">
                                            <i class="fa fa-trash-o text-white"></i>
                                        </a>
                                        <form id="delete-form-{{ $candidat->id }}" action="{{ route('admin.candidats.destroy', $candidat->id) }}"
                                              method="post" style="display: none;">
                                            @csrf @method('delete')
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE-->
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="smallmodal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="smallmodalLabel">Small Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        There are three species of zebras: the plains zebra, the mountain zebra and the Grévy's zebra. The plains zebra and the mountain
                        zebra belong to the subgenus Hippotigris, but Grévy's zebra is the sole species of subgenus Dolichohippus. The latter
                        resembles an ass, to which it is closely related, while the former two are more horse-like. All three belong to the
                        genus Equus, along with other living equids.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('script')
    <script>

    </script>
@endsection